// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KeyValueRequest.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KVRequest_CommandType int32

const (
	KVRequest_ISALIVE            KVRequest_CommandType = 0
	KVRequest_PUT                KVRequest_CommandType = 1
	KVRequest_GET                KVRequest_CommandType = 2
	KVRequest_REMOVE             KVRequest_CommandType = 3
	KVRequest_SHUTDOWN           KVRequest_CommandType = 4
	KVRequest_WIPEOUT            KVRequest_CommandType = 5
	KVRequest_GETPID             KVRequest_CommandType = 6
	KVRequest_GETMEMBERSHIPCOUNT KVRequest_CommandType = 7
)

var KVRequest_CommandType_name = map[int32]string{
	0: "ISALIVE",
	1: "PUT",
	2: "GET",
	3: "REMOVE",
	4: "SHUTDOWN",
	5: "WIPEOUT",
	6: "GETPID",
	7: "GETMEMBERSHIPCOUNT",
}

var KVRequest_CommandType_value = map[string]int32{
	"ISALIVE":            0,
	"PUT":                1,
	"GET":                2,
	"REMOVE":             3,
	"SHUTDOWN":           4,
	"WIPEOUT":            5,
	"GETPID":             6,
	"GETMEMBERSHIPCOUNT": 7,
}

func (x KVRequest_CommandType) String() string {
	return proto.EnumName(KVRequest_CommandType_name, int32(x))
}

func (KVRequest_CommandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_579450fc23673b8e, []int{0, 0}
}

type KVRequest struct {
	Command              int32    `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Version              int32    `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVRequest) Reset()         { *m = KVRequest{} }
func (m *KVRequest) String() string { return proto.CompactTextString(m) }
func (*KVRequest) ProtoMessage()    {}
func (*KVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_579450fc23673b8e, []int{0}
}

func (m *KVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVRequest.Unmarshal(m, b)
}
func (m *KVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVRequest.Marshal(b, m, deterministic)
}
func (m *KVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVRequest.Merge(m, src)
}
func (m *KVRequest) XXX_Size() int {
	return xxx_messageInfo_KVRequest.Size(m)
}
func (m *KVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KVRequest proto.InternalMessageInfo

func (m *KVRequest) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *KVRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KVRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KVRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.KVRequest_CommandType", KVRequest_CommandType_name, KVRequest_CommandType_value)
	proto.RegisterType((*KVRequest)(nil), "proto.KVRequest")
}

func init() { proto.RegisterFile("KeyValueRequest.proto", fileDescriptor_579450fc23673b8e) }

var fileDescriptor_579450fc23673b8e = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xc7, 0x5d, 0x4a, 0x5b, 0x1d, 0x38, 0x4c, 0x26, 0x6a, 0xf6, 0x48, 0x38, 0x71, 0xf2, 0xe2,
	0x13, 0x28, 0x4c, 0xca, 0x06, 0x4b, 0x9b, 0xed, 0xb4, 0x9c, 0x51, 0xf7, 0x60, 0x14, 0x8a, 0x7c,
	0x99, 0xbe, 0xad, 0x8f, 0x62, 0xb6, 0xc5, 0xd3, 0xfc, 0x7f, 0xf3, 0xf1, 0x4b, 0x06, 0xee, 0x16,
	0xae, 0xa9, 0xd6, 0x5f, 0x27, 0x67, 0xdd, 0xf7, 0xc9, 0x1d, 0x8e, 0x0f, 0xbb, 0x7d, 0x7d, 0xac,
	0x29, 0x6c, 0xcb, 0xf8, 0x57, 0xc1, 0xcd, 0xa2, 0xba, 0x8c, 0x48, 0x43, 0xfc, 0x56, 0x6f, 0x36,
	0xeb, 0xed, 0xbb, 0x56, 0x23, 0x35, 0x09, 0xed, 0x3f, 0x12, 0x42, 0xf0, 0xe9, 0x1a, 0xdd, 0x1b,
	0xa9, 0xc9, 0xd0, 0xfa, 0x48, 0xb7, 0x10, 0x9e, 0xbd, 0x56, 0x07, 0x6d, 0xaf, 0x03, 0x6f, 0x38,
	0xbb, 0xfd, 0xe1, 0xa3, 0xde, 0xea, 0x7e, 0x67, 0xb8, 0xe0, 0xf8, 0x07, 0x06, 0xd3, 0x4e, 0x26,
	0xcd, 0xce, 0xd1, 0x00, 0x62, 0x53, 0x3c, 0xbd, 0x98, 0x8a, 0xf1, 0x8a, 0x62, 0x08, 0xf2, 0x52,
	0x50, 0xf9, 0x90, 0xb0, 0x60, 0x8f, 0x00, 0x22, 0xcb, 0x69, 0x56, 0x31, 0x06, 0x34, 0x84, 0xeb,
	0x62, 0x5e, 0xca, 0x2c, 0x5b, 0x2d, 0xb1, 0xef, 0x0f, 0x57, 0x26, 0xe7, 0xac, 0x14, 0x0c, 0xfd,
	0x5a, 0xc2, 0x92, 0x9b, 0x19, 0x46, 0x74, 0x0f, 0x94, 0xb0, 0xa4, 0x9c, 0x3e, 0xb3, 0x2d, 0xe6,
	0x26, 0x9f, 0x66, 0xe5, 0x52, 0x30, 0x7e, 0x8d, 0xda, 0x4f, 0x1f, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0x9f, 0x4b, 0x3a, 0x09, 0x01, 0x00, 0x00,
}
