// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KeyValueResponse.proto

package tutorial

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KVResponse struct {
	ErrCode              uint32   `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Pid                  int32    `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Version              int32    `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	OverloadWaitTime     int32    `protobuf:"varint,5,opt,name=overloadWaitTime,proto3" json:"overloadWaitTime,omitempty"`
	MembershipCount      int32    `protobuf:"varint,6,opt,name=membershipCount,proto3" json:"membershipCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVResponse) Reset()         { *m = KVResponse{} }
func (m *KVResponse) String() string { return proto.CompactTextString(m) }
func (*KVResponse) ProtoMessage()    {}
func (*KVResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4704aca89e4fba3, []int{0}
}

func (m *KVResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVResponse.Unmarshal(m, b)
}
func (m *KVResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVResponse.Marshal(b, m, deterministic)
}
func (m *KVResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVResponse.Merge(m, src)
}
func (m *KVResponse) XXX_Size() int {
	return xxx_messageInfo_KVResponse.Size(m)
}
func (m *KVResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KVResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KVResponse proto.InternalMessageInfo

func (m *KVResponse) GetErrCode() uint32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *KVResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KVResponse) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *KVResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *KVResponse) GetOverloadWaitTime() int32 {
	if m != nil {
		return m.OverloadWaitTime
	}
	return 0
}

func (m *KVResponse) GetMembershipCount() int32 {
	if m != nil {
		return m.MembershipCount
	}
	return 0
}

func init() {
	proto.RegisterType((*KVResponse)(nil), "tutorial.KVResponse")
}

func init() { proto.RegisterFile("KeyValueResponse.proto", fileDescriptor_b4704aca89e4fba3) }

var fileDescriptor_b4704aca89e4fba3 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x89, 0xb5, 0x55, 0x0e, 0xc5, 0x12, 0x44, 0x32, 0x16, 0xa7, 0xe0, 0xe0, 0xe2, 0x23,
	0x74, 0xec, 0x16, 0xa4, 0xce, 0x29, 0x3d, 0x30, 0xd0, 0xf6, 0x42, 0x92, 0x16, 0x7c, 0x39, 0x9f,
	0x4d, 0x1a, 0xe9, 0xa2, 0xdb, 0x7d, 0xdf, 0xfd, 0xfc, 0xf0, 0xc3, 0xa9, 0xc2, 0x57, 0xad, 0xbb,
	0x11, 0x15, 0x7a, 0x4b, 0x83, 0xc7, 0xab, 0x75, 0x14, 0x88, 0x6f, 0xc3, 0x18, 0xc8, 0x19, 0xdd,
	0x9d, 0xdf, 0x0c, 0xa0, 0xaa, 0x97, 0x37, 0x17, 0xb0, 0x41, 0xe7, 0x4a, 0x6a, 0x51, 0xb0, 0x82,
	0xc9, 0xbd, 0x5a, 0x90, 0x1f, 0x21, 0x9d, 0xe6, 0x26, 0xb1, 0x2a, 0x98, 0xdc, 0xa9, 0x2f, 0xf0,
	0x1c, 0x12, 0x6b, 0x5a, 0x91, 0x14, 0x4c, 0xa6, 0x6a, 0x3e, 0xe7, 0x86, 0x09, 0x9d, 0x37, 0x34,
	0x88, 0x75, 0xb4, 0x0b, 0xf2, 0x0b, 0xe4, 0x34, 0xa1, 0xeb, 0x48, 0xb7, 0x0f, 0x6d, 0xc2, 0xdd,
	0xf4, 0x28, 0xd2, 0x18, 0xf9, 0xf3, 0x5c, 0xc2, 0xa1, 0xc7, 0xbe, 0x41, 0xe7, 0x9f, 0xc6, 0x96,
	0x34, 0x0e, 0x41, 0x64, 0x31, 0xfa, 0xab, 0x9b, 0x2c, 0x2e, 0xba, 0x7d, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xfc, 0x61, 0x4a, 0x50, 0xeb, 0x00, 0x00, 0x00,
}
