// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Message.proto

package tutorial

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Msg struct {
	MessageID            []byte   `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	CheckSum             uint64   `protobuf:"fixed64,3,opt,name=checkSum,proto3" json:"checkSum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b0f1bc979aed9f, []int{0}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetMessageID() []byte {
	if m != nil {
		return m.MessageID
	}
	return nil
}

func (m *Msg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Msg) GetCheckSum() uint64 {
	if m != nil {
		return m.CheckSum
	}
	return 0
}

func init() {
	proto.RegisterType((*Msg)(nil), "tutorial.Msg")
}

func init() { proto.RegisterFile("Message.proto", fileDescriptor_64b0f1bc979aed9f) }

var fileDescriptor_64b0f1bc979aed9f = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf5, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x29, 0x2d, 0xc9, 0x2f,
	0xca, 0x4c, 0xcc, 0x51, 0x8a, 0xe4, 0x62, 0xf6, 0x2d, 0x4e, 0x17, 0x92, 0xe1, 0xe2, 0xcc, 0x85,
	0xa8, 0xf0, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x42, 0x08, 0x08, 0x49, 0x70, 0xb1,
	0x17, 0x24, 0x56, 0xe6, 0xe4, 0x27, 0xa6, 0x48, 0x30, 0x81, 0xe5, 0x60, 0x5c, 0x21, 0x29, 0x2e,
	0x8e, 0xe4, 0x8c, 0xd4, 0xe4, 0xec, 0xe0, 0xd2, 0x5c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xb6, 0x20,
	0x38, 0x3f, 0x89, 0x0d, 0x6c, 0x97, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xa3, 0x17, 0xfb,
	0x7c, 0x00, 0x00, 0x00,
}
